### PR TITLE
Sury php

### LINKED ISSUE #8: Offer PHP7.1 installations via packages.sury.org
Because PHP 7.1 is :1st_place_medal:  

Depo: packages.sury.org/php

Thank you

### PR DESCRIPTION
**Pull request by nervo**
Closes #8

### CODE REVIEW

**Comment by tristanbes** [comment]
giphy

**Comment by nervo** [comment]
@tristanbes One little bug to fix, and that should be allright :)

**Comment by tristanbes** [comment]
giphy

**Comment by hyvs** [comment]
Yeah ! Congrats 💛

**Comment by tristanbes** [comment]
Thank you @nervo for your amazing work !

**Pull request merged**
